@startuml
[shadow-engine] <<static lib>> as engine
[shadow-light] <<exe>> as editor
[shadow-runner] <<exe>> as runner

[test-game] <<dll>> as game

engine <-editor
runner -> engine

game ..> engine

runner --> game : loads
editor --> game : loads

@enduml