@startuml
[shadow-light] <<exe>> as editor

    [shadow-entity] <<static lib>> as shentity
    [shadow-file-format] <<static lib>> as shff
    [shadow-reflection] <<static lib>> as shreflection
    [shadow-renderer] <<static lib>> as shrenderer
    [shadow-utilty] <<static lib>> as shutitily

    [shadow-engine] <<static/dynamic lib>> as shengine

    shentity --* shengine
    shff --* shengine
    shreflection --* shengine
    shrenderer --* shengine
    shutitily --* shengine


[shadow-runner] <<exe>> as runner

[test-game] <<dll>> as game

shengine <- editor
runner -> shengine

game ..> shengine : uses

runner --> game : loads
editor --> game : loads

@enduml