cc_binary(
    name = "example",
    srcs = ["main.cpp"],
    deps = [
        "@sdl2",
        "@rules_vulkan//vulkan:vulkan_cc_library",
        "@imgui_lib"
        ],  # <----- dep cc_library.Lib
)