load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "shadow-reflection",
    srcs = glob(["**/*.cpp"]),
    hdrs = [
        "SHObject.h"
    ],
    include_prefix = "",
    includes = [""],
    visibility = ["//visibility:public"],
)